"""
This type stub file was generated by pyright.
"""

import sys

if sys.version_info >= (3, 7, 0):
    GenericListClass = list
else:
    ...
def is_generic_list(service):
    ...

def ensure_forward_ref(self, service, factory, instance, **kwargs):
    ...

