MOCK_CONGRESS_API = {
    "https://api.propublica.org/congress/v1/116/senate/members.json": {
        "status": "OK",
        "copyright": " Copyright (c) 2021 Pro Publica Inc. All Rights Reserved.",
        "results": [
            {
                "congress": "116",
                "chamber": "Senate",
                "num_results": 102,
                "offset": 0,
                "members": [
                    {
                        "id": "A000360",
                        "title": "Senator, 2nd Class",
                        "short_title": "Sen.",
                        "api_uri": "https://api.propublica.org/congress/v1/members/A000360.json",
                        "first_name": "Lamar",
                        "middle_name": None,
                        "last_name": "Alexander",
                        "suffix": None,
                        "date_of_birth": "1940-07-03",
                        "gender": "M",
                        "party": "R",
                        "leadership_role": None,
                        "twitter_account": "SenAlexander",
                        "facebook_account": "senatorlamaralexander",
                        "youtube_account": "lamaralexander",
                        "govtrack_id": "300002",
                        "cspan_id": "5",
                        "votesmart_id": "15691",
                        "icpsr_id": "40304",
                        "crp_id": "N00009888",
                        "google_entity_id": "/m/01rbs3",
                        "fec_candidate_id": "S2TN00058",
                        "url": "https://www.alexander.senate.gov/public",
                        "rss_url": "https://www.alexander.senate.gov/public/?a=RSS.Feed",
                        "contact_form": "http://www.alexander.senate.gov/public/index.cfm?p=Email",
                        "in_office": False,
                        "cook_pvi": None,
                        "dw_nominate": 0.324,
                        "ideal_point": None,
                        "seniority": "17",
                        "next_election": "2020",
                        "total_votes": 717,
                        "missed_votes": 133,
                        "total_present": 0,
                        "last_updated": "2020-12-30 19:01:18 -0500",
                        "ocd_id": "ocd-division/country:us/state:tn",
                        "office": "455 Dirksen Senate Office Building",
                        "phone": "202-224-4944",
                        "fax": "202-228-3398",
                        "state": "TN",
                        "senate_class": "2",
                        "state_rank": "senior",
                        "lis_id": "S289",
                        "missed_votes_pct": 18.55,
                        "votes_with_party_pct": 96.55,
                        "votes_against_party_pct": 3.45,
                    },
                    {
                        "id": "B001230",
                        "title": "Senator, 1st Class",
                        "short_title": "Sen.",
                        "api_uri": "https://api.propublica.org/congress/v1/members/B001230.json",
                        "first_name": "Tammy",
                        "middle_name": None,
                        "last_name": "Baldwin",
                        "suffix": None,
                        "date_of_birth": "1962-02-11",
                        "gender": "F",
                        "party": "D",
                        "leadership_role": None,
                        "twitter_account": "SenatorBaldwin",
                        "facebook_account": "senatortammybaldwin",
                        "youtube_account": "witammybaldwin",
                        "govtrack_id": "400013",
                        "cspan_id": "57884",
                        "votesmart_id": "3470",
                        "icpsr_id": "29940",
                        "crp_id": "N00004367",
                        "google_entity_id": "/m/024v02",
                        "fec_candidate_id": "H8WI00018",
                        "url": "https://www.baldwin.senate.gov",
                        "rss_url": "https://www.baldwin.senate.gov/rss/feeds/?type=all",
                        "contact_form": "https://www.baldwin.senate.gov/feedback",
                        "in_office": False,
                        "cook_pvi": None,
                        "dw_nominate": -0.493,
                        "ideal_point": None,
                        "seniority": "7",
                        "next_election": "2024",
                        "total_votes": 717,
                        "missed_votes": 2,
                        "total_present": 1,
                        "last_updated": "2020-12-30 19:01:18 -0500",
                        "ocd_id": "ocd-division/country:us/state:wi",
                        "office": "709 Hart Senate Office Building",
                        "phone": "202-224-5653",
                        "fax": None,
                        "state": "WI",
                        "senate_class": "1",
                        "state_rank": "junior",
                        "lis_id": "S354",
                        "missed_votes_pct": 0.28,
                        "votes_with_party_pct": 94.65,
                        "votes_against_party_pct": 5.35,
                    },
                ],
            }
        ],
    },
    "https://api.propublica.org/congress/v1/116/house/members.json": {
        "status": "OK",
        "copyright": " Copyright (c) 2021 Pro Publica Inc. All Rights Reserved.",
        "results": [
            {
                "congress": "116",
                "chamber": "House",
                "num_results": 451,
                "offset": 0,
                "members": [
                    {
                        "id": "A000374",
                        "title": "Representative",
                        "short_title": "Rep.",
                        "api_uri": "https://api.propublica.org/congress/v1/members/A000374.json",
                        "first_name": "Ralph",
                        "middle_name": None,
                        "last_name": "Abraham",
                        "suffix": None,
                        "date_of_birth": "1954-09-16",
                        "gender": "M",
                        "party": "R",
                        "leadership_role": "",
                        "twitter_account": "RepAbraham",
                        "facebook_account": "CongressmanRalphAbraham",
                        "youtube_account": None,
                        "govtrack_id": "412630",
                        "cspan_id": "76236",
                        "votesmart_id": "155414",
                        "icpsr_id": "21522",
                        "crp_id": "N00036633",
                        "google_entity_id": "/m/012dwd7_",
                        "fec_candidate_id": "H4LA05221",
                        "url": "https://abraham.house.gov",
                        "rss_url": "https://abraham.house.gov/rss.xml",
                        "contact_form": None,
                        "in_office": False,
                        "cook_pvi": "R+15",
                        "dw_nominate": 0.541,
                        "ideal_point": None,
                        "seniority": "6",
                        "next_election": "2020",
                        "total_votes": 954,
                        "missed_votes": 377,
                        "total_present": 0,
                        "last_updated": "2020-12-31 18:30:50 -0500",
                        "ocd_id": "ocd-division/country:us/state:la/cd:5",
                        "office": "417 Cannon House Office Building",
                        "phone": "202-225-8490",
                        "fax": None,
                        "state": "LA",
                        "district": "5",
                        "at_large": False,
                        "geoid": "2205",
                        "missed_votes_pct": 39.52,
                        "votes_with_party_pct": 94.93,
                        "votes_against_party_pct": 4.90,
                    },
                    {
                        "id": "A000370",
                        "title": "Representative",
                        "short_title": "Rep.",
                        "api_uri": "https://api.propublica.org/congress/v1/members/A000370.json",
                        "first_name": "Alma",
                        "middle_name": None,
                        "last_name": "Adams",
                        "suffix": None,
                        "date_of_birth": "1946-05-27",
                        "gender": "F",
                        "party": "D",
                        "leadership_role": None,
                        "twitter_account": "RepAdams",
                        "facebook_account": "CongresswomanAdams",
                        "youtube_account": None,
                        "govtrack_id": "412607",
                        "cspan_id": "76386",
                        "votesmart_id": "5935",
                        "icpsr_id": "21545",
                        "crp_id": "N00035451",
                        "google_entity_id": "/m/02b45d",
                        "fec_candidate_id": "H4NC12100",
                        "url": "https://adams.house.gov",
                        "rss_url": "https://adams.house.gov/rss.xml",
                        "contact_form": None,
                        "in_office": False,
                        "cook_pvi": "D+18",
                        "dw_nominate": -0.465,
                        "ideal_point": None,
                        "seniority": "8",
                        "next_election": "2020",
                        "total_votes": 954,
                        "missed_votes": 26,
                        "total_present": 0,
                        "last_updated": "2020-12-31 18:30:55 -0500",
                        "ocd_id": "ocd-division/country:us/state:nc/cd:12",
                        "office": "2436 Rayburn House Office Building",
                        "phone": "202-225-1510",
                        "fax": None,
                        "state": "NC",
                        "district": "12",
                        "at_large": False,
                        "geoid": "3712",
                        "missed_votes_pct": 2.73,
                        "votes_with_party_pct": 99.24,
                        "votes_against_party_pct": 0.65,
                    },
                ],
            }
        ],
    },
}
