"""
This type stub file was generated by pyright.
"""

from .states import OBSOLETE, STATES, STATES_AND_TERRITORIES, STATES_CONTIGUOUS, STATES_CONTINENTAL, TERRITORIES
from .unitedstatesofamerica import *

